version: "3"

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml
        labels:
            - "traefic.enable=true"
            - "traefik.http.routers.api.rule=Host('monitor.raspberrypi4')"
            - "traefik.http.routers.api.service=api@internal"
        networks:
            - web

networks:
    web:
        external: true
