defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "karl@kedrovsky.com"
  storage = "acme.json"
  # staging server
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  # production server
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    entryPoint = "web"

[api]
  insecure = false
  dashboard = true
  debug = false

[providers.docker]
  watch = true
  network = "web"
  exposedbydefault = false
