defaultEntryPoints = ["http"]

[entryPoints.dashboard]
#  address = ":8080"
#  [entryPoints.dashboard.auth]
#    [entryPoints.dashboard.auth.basic]
#      users = ["admin:$apr1$Yi5smEit$xxkZGZwHM0l5WgZ1RTk96."]
[entryPoints]
  [entryPoints.web]
  address = ":80"

[api]
  insecure = true
  dashboard = true
  debug = true

[providers.docker]
  watch = true
  network = "web"
  exposedbydefault = false
